apiVersion: v2
appVersion: '2.0'
description: Calarm Collection CIS Module
name: calarm-collection-cis
version: 1.0.5
dependencies:
  - name: postgresql
    version: 10.14.3
    repository: '@bitnami'
    alias: calarm-db
    tags:
      - kubeDb

maintainers:
  - name: JeffreyGarrett
    email: jeff.garrett@dhcs.ca.gov
