{{ if .Values.cisSecret }}
# Connection info for AWS-hosted DB from AWS Secrets Manager
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: calarm-collection-cis-secret
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  #roleArn: arn:aws:iam::123456789012:role/test-role
  dataFrom:
    - {{ .Values.cisSecret }}
{{- end }}
