apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: calarm-collection-cis-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: https
      number: 443
      protocol: HTTP
    hosts:
    - {{ .Values.gateway.domainWildcard | quote }}
