apiVersion: v1
kind: Service
metadata:
  name: calarm-collection-cis-service
  labels:
    app: calarm
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: calarm
